//
//  MockDreamDatabase.swift
//  AIEngineApp
//
//  Created by i564407 on 10/3/25.
//


import Foundation

struct MockDreamDatabase {
    
    static let dreamEntries: [DreamEntry] = [
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -10, to: .now)!,
                   title: "期末考试",
                   summary: "又梦到了大学的期末考试，试卷一片空白，非常焦虑。",
                   keywords: ["考试", "焦虑", "学校"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -25, to: .now)!,
                   title: "深海潜水",
                   summary: "我潜入了深不见底的蓝色大海，看到了发光的水母和巨大的鲸鱼。",
                   keywords: ["海洋", "潜水", "鲸鱼"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -40, to: .now)!,
                   title: "再次飞行",
                   summary: "这次是在一片广阔的森林上空飞行，下面是无尽的绿色。",
                   keywords: ["飞行", "森林", "自然"]),

        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "牙齿脱落",
                   summary: "梦里我的牙齿一颗颗地掉了下来，没有血，但感觉很恐慌。",
                   keywords: ["牙齿", "脱落", "恐慌"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "被追赶",
                   summary: "在一个无人的街道上，我被一个看不清脸的黑影追赶，拼命地跑却跑不快。",
                   keywords: ["追赶", "恐惧", "奔跑"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "回到童年的家",
                   summary: "我回到了小时候住的老房子，一切都和记忆中一样，阳光很温暖。",
                   keywords: ["家", "童年", "怀旧"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "在沙漠中行走",
                   summary: "我一个人在无垠的沙漠里行走，口渴难耐，远方有海市蜃楼。",
                   keywords: ["沙漠", "孤独", "行走"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "会说话的猫",
                   summary: "家里的猫突然开口对我说话，我们聊了一整个下午的人生哲理。",
                   keywords: ["猫", "说话", "奇幻"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "错过火车",
                   summary: "我提着行李在站台狂奔，眼睁睁地看着火车在我面前开走。",
                   keywords: ["错过", "火车", "焦虑"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "中了彩票",
                   summary: "梦见自己中了巨额彩票，欣喜若狂，开始计划环游世界。",
                   keywords: ["彩票", "财富", "喜悦"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "无尽的楼梯",
                   summary: "我一直在向上爬一个永远没有尽头的旋转楼梯，感觉很疲惫。",
                   keywords: ["楼梯", "重复", "疲惫"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "与逝去亲人重逢",
                   summary: "梦里见到了已经去世的奶奶，她对我微笑，感觉很安心。",
                   keywords: ["亲人", "重逢", "思念"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "世界末日",
                   summary: "天空变成红色，陨石坠落，我和家人在一起，准备迎接终结。",
                   keywords: ["末日", "灾难", "家庭"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "拥有超能力",
                   summary: "我发现自己可以瞬间移动，于是在世界各地穿梭，看遍了名胜古迹。",
                   keywords: ["超能力", "瞬间移动", "冒险"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "在雨中漫步",
                   summary: "独自一人在淅淅沥沥的小雨中漫步，没有打伞，心情平静。",
                   keywords: ["雨", "漫步", "平静"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "变成巨人",
                   summary: "我变成了巨人，城市像积木一样在我脚下，每一步都小心翼翼。",
                   keywords: ["巨人", "城市", "力量"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "迷宫",
                   summary: "被困在一个由绿色植物构成的巨大迷宫里，找不到出口。",
                   keywords: ["迷宫", "困惑", "寻找"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "水下城市",
                   summary: "我来到了一个宏伟的水下城市，居民都是鱼类，建筑由珊瑚构成。",
                   keywords: ["海洋", "城市", "奇幻"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "公开演讲失败",
                   summary: "站在台上准备演讲，却发现自己什么都说不出来，台下的人都在笑。",
                   keywords: ["演讲", "失败", "尴尬"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "森林小屋",
                   summary: "在森林深处发现一个温暖的小木屋，里面生着火，感觉很安全。",
                   keywords: ["森林", "小屋", "安全"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "时间旅行",
                   summary: "我乘坐时间机器回到了古代，看到了恐龙在地球上漫步。",
                   keywords: ["时间旅行", "恐龙", "冒险"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "高空坠落",
                   summary: "从摩天大楼的顶端坠落，失重感非常真实，在落地前惊醒。",
                   keywords: ["坠落", "恐惧", "高楼"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "和偶像共进晚餐",
                   summary: "我和我最喜欢的明星一起吃饭，聊得很开心，像老朋友一样。",
                   keywords: ["偶像", "晚餐", "兴奋"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "找不到回家的路",
                   summary: "在一个陌生的城市里，我迷路了，手机也没电，怎么也找不到回家的路。",
                   keywords: ["迷路", "焦虑", "城市"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "在月球上行走",
                   summary: "我穿着宇航服，在月球表面行走，地球像一颗蓝色的宝石挂在天上。",
                   keywords: ["月球", "太空", "壮观"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "僵尸来袭",
                   summary: "城市里爆发了僵尸病毒，我和一群幸存者在超市里建立防御。",
                   keywords: ["僵尸", "生存", "恐惧"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "参加盛大舞会",
                   summary: "我穿着华丽的礼服，在一个金碧辉煌的大厅里跳舞，音乐很美。",
                   keywords: ["舞会", "华丽", "浪漫"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "解开一个谜题",
                   summary: "我像侦探一样，通过寻找线索，最终解开了一个复杂的谋杀案谜题。",
                   keywords: ["谜题", "侦探", "智慧"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "重返校园",
                   summary: "我又回到了高中教室，和同学一起上课，感觉很怀念。",
                   keywords: ["学校", "怀旧", "同学"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "在海滩上看日出",
                   summary: "在空无一人的海滩上，看着太阳缓缓从海平面升起，天空被染成金色。",
                   keywords: ["海滩", "日出", "宁静"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "与动物交谈",
                   summary: "森林里的所有动物都能听懂我说话，我也能理解它们，我们开了一个会议。",
                   keywords: ["动物", "交谈", "自然"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "食物构成的世界",
                   summary: "我来到了一个由糖果和蛋糕构成的世界，河流是巧克力，山是冰淇淋。",
                   keywords: ["食物", "奇幻", "甜蜜"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "裸体出现在公共场所",
                   summary: "突然发现自己在人群中没有穿衣服，感到非常羞愧和恐慌。",
                   keywords: ["裸体", "尴尬", "脆弱"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "在图书馆找到一本魔法书",
                   summary: "在图书馆的角落里，我找到了一本古老的魔法书，学会了第一个咒语。",
                   keywords: ["魔法", "书", "秘密"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "驾驶赛车",
                   summary: "我成了一名赛车手，在赛道上疾驰，感受速度与激情。",
                   keywords: ["赛车", "速度", "兴奋"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "冰雪世界",
                   summary: "整个世界都被冰雪覆盖，我住在一个晶莹剔透的冰宫里。",
                   keywords: ["冰雪", "寒冷", "美丽"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "战争与和平",
                   summary: "我身处战场，炮火连天，但内心却异常渴望和平。",
                   keywords: ["战争", "冲突", "和平"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "修复破碎的物品",
                   summary: "我有一种能力，可以完美地修复任何破碎的物品，比如花瓶和镜子。",
                   keywords: ["修复", "能力", "完整"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "无法发出声音",
                   summary: "我想大声呼救，却发现自己怎么也发不出声音，喉咙像被堵住了一样。",
                   keywords: ["失声", "无助", "压抑"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "在画中世界旅行",
                   summary: "我走进了一幅名画，和画中的人物一起生活了一天。",
                   keywords: ["画", "艺术", "旅行"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "火山爆发",
                   summary: "我站在远处的一座山上，看着远方的火山爆发出滚滚浓烟和岩浆。",
                   keywords: ["火山", "爆发", "力量"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "发现宝藏",
                   summary: "根据一张旧地图，我历尽千辛万苦，终于找到了埋藏在地下的宝藏箱。",
                   keywords: ["宝藏", "地图", "发现"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "婚礼",
                   summary: "我参加了一场婚礼，但新郎或新娘的脸却一直看不清楚。",
                   keywords: ["婚礼", "模糊", "关系"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "机器人伴侣",
                   summary: "我拥有一个高度智能的机器人伴侣，它比任何人都懂我。",
                   keywords: ["机器人", "未来", "陪伴"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "天空之城",
                   summary: "我到达了一座漂浮在天空中的城市，建筑风格奇特，交通工具是飞毯。",
                   keywords: ["天空", "城市", "奇幻"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "洪水",
                   summary: "大水淹没了我的家，我只能抱着一块木板在水中漂流。",
                   keywords: ["洪水", "灾难", "失控"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "变成另一个人",
                   summary: "我从镜子里看到一张完全陌生的脸，发现自己变成了另一个人。",
                   keywords: ["身份", "陌生", "困惑"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "简单的拥抱",
                   summary: "梦里没有什么特别的情节，只是一个来自朋友的温暖而长久的拥抱。",
                   keywords: ["拥抱", "温暖", "友情"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "鬼屋探险",
                   summary: "我和朋友们一起去一个传说中的鬼屋探险，听到了奇怪的声音。",
                   keywords: ["鬼屋", "探险", "恐惧"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "在水面上行走",
                   summary: "我发现自己可以在湖面上行走，就像在平地上一样，感觉很神奇。",
                   keywords: ["水面", "行走", "神奇"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "一场精彩的音乐会",
                   summary: "我正在观看一场乐队的现场演出，音乐非常震撼，全场气氛热烈。",
                   keywords: ["音乐会", "音乐", "激情"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "写不完的作业",
                   summary: "桌上堆满了永远也写不完的作业，天马上就要亮了。",
                   keywords: ["作业", "压力", "焦虑"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "外星人接触",
                   summary: "一艘UFO降落在我的后院，外星人走了出来，并友好地向我招手。",
                   keywords: ["外星人", "UFO", "接触"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "巨大的图书馆",
                   summary: "我置身于一个巨大无比的图书馆，书架直通天花板，收藏了世界上所有的知识。",
                   keywords: ["图书馆", "知识", "浩瀚"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "爬山",
                   summary: "我正在奋力攀登一座高山，虽然很累，但山顶的风景一定很美。",
                   keywords: ["爬山", "努力", "目标"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "与历史人物对话",
                   summary: "我见到了爱因斯坦，并和他讨论了关于时空的问题。",
                   keywords: ["历史", "对话", "智慧"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "失重",
                   summary: "我在房间里漂浮了起来，所有家具也都漂浮着，失去了重力。",
                   keywords: ["失重", "漂浮", "自由"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "一场追逐游戏",
                   summary: "和童年的伙伴们在草地上玩追逐游戏，阳光明媚，笑声不断。",
                   keywords: ["游戏", "童年", "快乐"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "植物疯长",
                   summary: "房间里的植物突然开始疯狂生长，藤蔓爬满了整个屋子。",
                   keywords: ["植物", "生长", "失控"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "一场奇怪的派对",
                   summary: "我参加了一个派对，所有人都戴着动物面具，行为举止很怪异。",
                   keywords: ["派对", "面具", "神秘"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "找到丢失的物品",
                   summary: "我找到了 давно 丢失的一件珍贵物品，失而复得的感觉真好。",
                   keywords: ["丢失", "找回", "喜悦"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "照顾一个婴儿",
                   summary: "我正在照顾一个可爱的婴儿，虽然手忙脚乱，但感觉很温馨。",
                   keywords: ["婴儿", "照顾", "责任"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "看不见的墙",
                   summary: "我向前走，却撞到了一堵看不见的墙，无论如何都无法通过。",
                   keywords: ["墙", "阻碍", "困境"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "彩虹色的河流",
                   summary: "我看到一条流淌着彩虹颜色液体的河流，非常绚丽。",
                   keywords: ["彩虹", "河流", "美丽"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "在舞台上表演",
                   summary: "我站在聚光灯下的舞台上，为座无虚席的观众表演，内心既紧张又兴奋。",
                   keywords: ["舞台", "表演", "关注"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "一场大雪",
                   summary: "窗外下着鹅毛大雪，整个世界都变成了白色，非常安静。",
                   keywords: ["雪", "安静", "冬天"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "解救一只动物",
                   summary: "我从陷阱中解救了一只受伤的小狐狸，并为它包扎了伤口。",
                   keywords: ["解救", "动物", "善良"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "镜子里的自己",
                   summary: "镜子里的自己突然对我露出了一个诡异的微笑，和我做的表情不一样。",
                   keywords: ["镜子", "自己", "诡异"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "学习一项新技能",
                   summary: "我梦见自己在一夜之间学会了弹钢琴，弹奏出美妙的乐曲。",
                   keywords: ["学习", "技能", "成就"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "空荡的城市",
                   summary: "我走在熟悉的城市街道上，但周围一个人也没有，空空荡荡。",
                   keywords: ["空城", "孤独", "寂静"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "一场争吵",
                   summary: "我和一个好朋友发生了激烈的争吵，醒来后心情很低落。",
                   keywords: ["争吵", "朋友", "冲突"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "地下洞穴探险",
                   summary: "我举着火把，在一个巨大的地下洞穴中探险，看到了钟乳石和地下河。",
                   keywords: ["洞穴", "探险", "黑暗"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "一场盛宴",
                   summary: "桌上摆满了各种美食，我却一点也吃不下去。",
                   keywords: ["食物", "盛宴", "欲望"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "风暴来临",
                   summary: "乌云密布，狂风大作，一场巨大的海上风暴即将来临。",
                   keywords: ["风暴", "海洋", "危机"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "制作陶器",
                   summary: "我正在陶艺机上制作一个花瓶，感受着湿润的陶土在指尖成形。",
                   keywords: ["陶艺", "创造", "专注"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "迷雾森林",
                   summary: "我走进了一片笼罩着浓雾的森林，能见度很低，分不清方向。",
                   keywords: ["森林", "迷雾", "迷茫"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "获得一枚奖牌",
                   summary: "我因为某项成就获得了一枚金光闪闪的奖牌，感到非常自豪。",
                   keywords: ["奖牌", "荣誉", "成就"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "在屋顶上看星星",
                   summary: "和某人一起躺在屋顶上，看着满天的繁星，聊着未来的梦想。",
                   keywords: ["星星", "屋顶", "浪漫"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "一场葬礼",
                   summary: "我参加了一场葬礼，气氛肃穆，但我看不清是谁去世了。",
                   keywords: ["葬礼", "悲伤", "结束"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "穿越火海",
                   summary: "为了到达某个地方，我必须勇敢地穿越一片燃烧的火海。",
                   keywords: ["火", "穿越", "挑战"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "奇怪的电话",
                   summary: "电话铃响了，另一端却只有静电的嘶嘶声，没有人说话。",
                   keywords: ["电话", "奇怪", "未知"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "建造房子",
                   summary: "我正在一砖一瓦地建造属于自己的房子，虽然进度缓慢但很满足。",
                   keywords: ["建造", "房子", "努力"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "重力颠倒",
                   summary: "房间里的重力突然颠倒，我站在了天花板上，看着地板在我“头顶”。",
                   keywords: ["重力", "颠倒", "混乱"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "一次成功的考试",
                   summary: "梦到一场重要的考试，我所有题目都会做，感觉胸有成竹。",
                   keywords: ["考试", "成功", "自信"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "沙漠绿洲",
                   summary: "在沙漠中绝望之时，我发现了一片美丽的绿洲，有清澈的泉水和棕榈树。",
                   keywords: ["沙漠", "绿洲", "希望"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "和解",
                   summary: "我和一个很久没有联系的朋友见了面，解开了过去的心结，互相原谅了。",
                   keywords: ["和解", "朋友", "原谅"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "缩小",
                   summary: "我身体突然缩小，变得像蚂蚁一样大，周围的世界变得无比巨大。",
                   keywords: ["缩小", "巨大", "无力"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "被遗忘的旋律",
                   summary: "我一直在哼唱一首非常熟悉的旋律，却怎么也想不起来它的名字。",
                   keywords: ["旋律", "遗忘", "记忆"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "一场平静的下午茶",
                   summary: "在一个花园里，我和朋友们一起享受着下午茶，阳光正好，微风不燥。",
                   keywords: ["下午茶", "朋友", "惬意"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "逃离",
                   summary: "我正在从一个像监狱一样的地方逃跑，身后有警报声响起。",
                   keywords: ["逃离", "束缚", "自由"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "龙",
                   summary: "一条巨大的东方龙在云层中盘旋，它的鳞片闪闪发光，充满了威严。",
                   keywords: ["龙", "神话", "力量"]),
        DreamEntry(date: Calendar.current.date(byAdding: .day, value: -Int.random(in: 1...1095), to: .now)!,
                   title: "春天",
                   summary: "我看到枯萎的树枝长出了新芽，冰雪融化，万物复苏，春天来了。",
                   keywords: ["春天", "复苏", "新生"]),
    ]
    
    /// 模拟数据库查询
    /// - Parameters:
    ///   - keyword: 搜索的关键词
    ///   - period: 时间范围 (这里只简单实现 "last_month")
    /// - Returns: 符合条件的梦境数组
    static func search(keyword: String?, period: String?) -> [DreamEntry] {
        var results = dreamEntries
        
        // 1. 根据关键词过滤
        if let keyword = keyword, !keyword.isEmpty {
            results = results.filter { $0.keywords.contains(keyword) || $0.title.contains(keyword) || $0.summary.contains(keyword) }
        }
        
        // 2. 根据时间范围过滤
        if period == "last_three_years" {
            let threeYearsAgoDate = Calendar.current.date(byAdding: .year, value: -3, to: .now)!
            let threeYearsAgoString = threeYearsAgoDate.ISO8601Format()
            results = results.filter { $0.date >= threeYearsAgoString }
        }
        
        return results
    }
}
